### ISSUE TITLE
`getLogo` not implemented

### ISSUE THREAD

**Issue by letmejustputthishere** [Psychedelic/wicp#21]
I tried the following
```
❯ dfx canister --network=ic call --query utozz-siaaa-aaaam-qaaxq-cai getLogo

The Replica returned an error: code 3, message: "IC0302: Canister utozz-siaaa-aaaam-qaaxq-cai has no query method 'getLogo'"
```

**Comment by b0xtch** [comment]
> I tried the following
> 
> ```
> ❯ dfx canister --network=ic call --query utozz-siaaa-aaaam-qaaxq-cai getLogo
> 
> The Replica returned an error: code 3, message: "IC0302: Canister utozz-siaaa-aaaam-qaaxq-cai has no query method 'getLogo'"
> ```

Hey, The function should just be`logo`
https://github.com/Psychedelic/wicp/blob/main/wicp/wicp.did#L53
