### ISSUE TITLE
Can not import wicp to plug wallet

### ISSUE THREAD

**Issue by jim3333** [Psychedelic/wicp#7]
![image](https://user-images.githubusercontent.com/70828593/145108425-b797bd7e-19f7-4f25-aae5-216a4eb2542b.png)

```
Canister utozz-siaaa-aaaam-qaaxq-cai has no query method 'extensions'
```

**Comment by jim3333** [comment]
When plug wallet support mint/withdraw wcip. `dfx` is a development tool, plug more friendly.

**Comment by ferencdg** [comment]
as far as I know you will be able to mint through the 'Sonic' decentralized exchange where you can swap your ICP to WICP and back

@rocky-fleek
